// config/navigation/platformAdminNav.js
/**
 * Master Navigation Configuration — Aggregator
 * Imports subsystem-specific navigation definitions (accountsNav, tenantNav, kpiNav, structureNav, billingNav, reviewsNav, reportsNav)
 * and exports unified role navigation groups for sidebar components.
 */

import {
  ACCOUNTS_SUPER_ADMIN_NAV_GROUPS,
  ACCOUNTS_SUPER_ADMIN_GROUP_LABELS,
  ACCOUNTS_SUPER_ADMIN_DEFAULT_EXPANDED,
  ACCOUNTS_CLIENT_ADMIN_NAV_GROUPS,
  ACCOUNTS_CLIENT_ADMIN_GROUP_LABELS,
  ACCOUNTS_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ACCOUNTS_EXECUTIVE_NAV_GROUPS,
  ACCOUNTS_EXECUTIVE_GROUP_LABELS,
  ACCOUNTS_EXECUTIVE_DEFAULT_EXPANDED,
  ACCOUNTS_MANAGER_NAV_GROUPS,
  ACCOUNTS_MANAGER_GROUP_LABELS,
  ACCOUNTS_MANAGER_DEFAULT_EXPANDED,
  ACCOUNTS_STAFF_NAV_GROUPS,
  ACCOUNTS_STAFF_GROUP_LABELS,
  ACCOUNTS_STAFF_DEFAULT_EXPANDED,
  ACCOUNTS_CHAMPION_NAV_GROUPS,
  ACCOUNTS_CHAMPION_GROUP_LABELS,
  ACCOUNTS_CHAMPION_DEFAULT_EXPANDED,
  ACCOUNTS_READ_ONLY_NAV_GROUPS,
  ACCOUNTS_READ_ONLY_GROUP_LABELS,
  ACCOUNTS_READ_ONLY_DEFAULT_EXPANDED,
  isAccountsRouteActive,
} from './accountsNav';

import {
  TENANT_SUPER_ADMIN_NAV_GROUPS,
  TENANT_SUPER_ADMIN_GROUP_LABELS,
  TENANT_SUPER_ADMIN_DEFAULT_EXPANDED,
  TENANT_CLIENT_ADMIN_NAV_GROUPS,
  TENANT_CLIENT_ADMIN_GROUP_LABELS,
  TENANT_CLIENT_ADMIN_DEFAULT_EXPANDED,
  isTenantRouteActive,
} from './tenantNav';

import {
  KPI_SUPER_ADMIN_NAV_GROUPS,
  KPI_SUPER_ADMIN_GROUP_LABELS,
  KPI_SUPER_ADMIN_DEFAULT_EXPANDED,
  KPI_CLIENT_ADMIN_NAV_GROUPS,
  KPI_CLIENT_ADMIN_GROUP_LABELS,
  KPI_CLIENT_ADMIN_DEFAULT_EXPANDED,
  KPI_CHAMPION_NAV_GROUPS,
  KPI_CHAMPION_GROUP_LABELS,
  KPI_CHAMPION_DEFAULT_EXPANDED,
  KPI_EXECUTIVE_NAV_GROUPS,
  KPI_EXECUTIVE_GROUP_LABELS,
  KPI_EXECUTIVE_DEFAULT_EXPANDED,
  KPI_MANAGER_NAV_GROUPS,
  KPI_MANAGER_GROUP_LABELS,
  KPI_MANAGER_DEFAULT_EXPANDED,
  KPI_STAFF_NAV_GROUPS,
  KPI_STAFF_GROUP_LABELS,
  KPI_STAFF_DEFAULT_EXPANDED,
  KPI_READ_ONLY_NAV_GROUPS,
  KPI_READ_ONLY_GROUP_LABELS,
  KPI_READ_ONLY_DEFAULT_EXPANDED,
  isKpiRouteActive,
} from './kpiNav';

import {
  STRUCTURE_SUPER_ADMIN_NAV_GROUPS,
  STRUCTURE_SUPER_ADMIN_GROUP_LABELS,
  STRUCTURE_SUPER_ADMIN_DEFAULT_EXPANDED,
  STRUCTURE_CLIENT_ADMIN_NAV_GROUPS,
  STRUCTURE_CLIENT_ADMIN_GROUP_LABELS,
  STRUCTURE_CLIENT_ADMIN_DEFAULT_EXPANDED,
  STRUCTURE_EXECUTIVE_NAV_GROUPS,
  STRUCTURE_EXECUTIVE_GROUP_LABELS,
  STRUCTURE_EXECUTIVE_DEFAULT_EXPANDED,
  STRUCTURE_CHAMPION_NAV_GROUPS,
  STRUCTURE_CHAMPION_GROUP_LABELS,
  STRUCTURE_CHAMPION_DEFAULT_EXPANDED,
  STRUCTURE_MANAGER_NAV_GROUPS,
  STRUCTURE_MANAGER_GROUP_LABELS,
  STRUCTURE_MANAGER_DEFAULT_EXPANDED,
  STRUCTURE_STAFF_NAV_GROUPS,
  STRUCTURE_STAFF_GROUP_LABELS,
  STRUCTURE_STAFF_DEFAULT_EXPANDED,
  STRUCTURE_READ_ONLY_NAV_GROUPS,
  STRUCTURE_READ_ONLY_GROUP_LABELS,
  STRUCTURE_READ_ONLY_DEFAULT_EXPANDED,
  isStructureRouteActive,
} from './structureNav';

import {
  BILLING_SUPER_ADMIN_NAV_GROUPS,
  BILLING_SUPER_ADMIN_GROUP_LABELS,
  BILLING_SUPER_ADMIN_DEFAULT_EXPANDED,
  BILLING_CLIENT_ADMIN_NAV_GROUPS,
  BILLING_CLIENT_ADMIN_GROUP_LABELS,
  BILLING_CLIENT_ADMIN_DEFAULT_EXPANDED,
  isBillingRouteActive,
} from './billingNav';

import {
  REVIEWS_SUPER_ADMIN_NAV_GROUPS,
  REVIEWS_SUPER_ADMIN_GROUP_LABELS,
  REVIEWS_SUPER_ADMIN_DEFAULT_EXPANDED,
  REVIEWS_CLIENT_ADMIN_NAV_GROUPS,
  REVIEWS_CLIENT_ADMIN_GROUP_LABELS,
  REVIEWS_CLIENT_ADMIN_DEFAULT_EXPANDED,
  REVIEWS_EXECUTIVE_NAV_GROUPS,
  REVIEWS_EXECUTIVE_GROUP_LABELS,
  REVIEWS_EXECUTIVE_DEFAULT_EXPANDED,
  REVIEWS_MANAGER_NAV_GROUPS,
  REVIEWS_MANAGER_GROUP_LABELS,
  REVIEWS_MANAGER_DEFAULT_EXPANDED,
  REVIEWS_STAFF_NAV_GROUPS,
  REVIEWS_STAFF_GROUP_LABELS,
  REVIEWS_STAFF_DEFAULT_EXPANDED,
  REVIEWS_CHAMPION_NAV_GROUPS,
  REVIEWS_CHAMPION_GROUP_LABELS,
  REVIEWS_CHAMPION_DEFAULT_EXPANDED,
  REVIEWS_READ_ONLY_NAV_GROUPS,
  REVIEWS_READ_ONLY_GROUP_LABELS,
  REVIEWS_READ_ONLY_DEFAULT_EXPANDED,
  isReviewsRouteActive,
} from './reviewsNav';

import {
  REPORTS_SUPER_ADMIN_NAV_GROUPS,
  REPORTS_SUPER_ADMIN_GROUP_LABELS,
  REPORTS_SUPER_ADMIN_DEFAULT_EXPANDED,
  REPORTS_CLIENT_ADMIN_NAV_GROUPS,
  REPORTS_CLIENT_ADMIN_GROUP_LABELS,
  REPORTS_CLIENT_ADMIN_DEFAULT_EXPANDED,
  REPORTS_EXECUTIVE_NAV_GROUPS,
  REPORTS_EXECUTIVE_GROUP_LABELS,
  REPORTS_EXECUTIVE_DEFAULT_EXPANDED,
  REPORTS_MANAGER_NAV_GROUPS,
  REPORTS_MANAGER_GROUP_LABELS,
  REPORTS_MANAGER_DEFAULT_EXPANDED,
  REPORTS_STAFF_NAV_GROUPS,
  REPORTS_STAFF_GROUP_LABELS,
  REPORTS_STAFF_DEFAULT_EXPANDED,
  REPORTS_CHAMPION_NAV_GROUPS,
  REPORTS_CHAMPION_GROUP_LABELS,
  REPORTS_CHAMPION_DEFAULT_EXPANDED,
  REPORTS_READ_ONLY_NAV_GROUPS,
  REPORTS_READ_ONLY_GROUP_LABELS,
  REPORTS_READ_ONLY_DEFAULT_EXPANDED,
  isReportsRouteActive,
} from './reportsNav';

import {
  CONFIG_SUPER_ADMIN_NAV_GROUPS,
  CONFIG_SUPER_ADMIN_GROUP_LABELS,
  CONFIG_SUPER_ADMIN_DEFAULT_EXPANDED,
  CONFIG_CLIENT_ADMIN_NAV_GROUPS,
  CONFIG_CLIENT_ADMIN_GROUP_LABELS,
  CONFIG_CLIENT_ADMIN_DEFAULT_EXPANDED,
  isConfigRouteActive,
} from './configNav';

// Re-export Accounts, Tenant, KPI, Structure, Billing, Reviews, Reports & Config Nav Items & Groups
export * from './accountsNav';
export * from './tenantNav';
export * from './kpiNav';
export * from './structureNav';
export * from './billingNav';
export * from './reviewsNav';
export * from './reportsNav';
export * from './configNav';

// ============================================
// ROLE NAVIGATION GROUPS (Aggregated Across Subsystems)
// ============================================
export const SUPER_ADMIN_NAV_GROUPS = {
  ...ACCOUNTS_SUPER_ADMIN_NAV_GROUPS,
  ...TENANT_SUPER_ADMIN_NAV_GROUPS,
  ...STRUCTURE_SUPER_ADMIN_NAV_GROUPS,
  ...KPI_SUPER_ADMIN_NAV_GROUPS,
  ...BILLING_SUPER_ADMIN_NAV_GROUPS,
  ...REVIEWS_SUPER_ADMIN_NAV_GROUPS,
  ...REPORTS_SUPER_ADMIN_NAV_GROUPS,
  ...CONFIG_SUPER_ADMIN_NAV_GROUPS,
};

export const SUPER_ADMIN_GROUP_LABELS = {
  ...ACCOUNTS_SUPER_ADMIN_GROUP_LABELS,
  ...TENANT_SUPER_ADMIN_GROUP_LABELS,
  ...STRUCTURE_SUPER_ADMIN_GROUP_LABELS,
  ...KPI_SUPER_ADMIN_GROUP_LABELS,
  ...BILLING_SUPER_ADMIN_GROUP_LABELS,
  ...REVIEWS_SUPER_ADMIN_GROUP_LABELS,
  ...REPORTS_SUPER_ADMIN_GROUP_LABELS,
  ...CONFIG_SUPER_ADMIN_GROUP_LABELS,
};

export const SUPER_ADMIN_DEFAULT_EXPANDED = {
  ...ACCOUNTS_SUPER_ADMIN_DEFAULT_EXPANDED,
  ...TENANT_SUPER_ADMIN_DEFAULT_EXPANDED,
  ...STRUCTURE_SUPER_ADMIN_DEFAULT_EXPANDED,
  ...KPI_SUPER_ADMIN_DEFAULT_EXPANDED,
  ...BILLING_SUPER_ADMIN_DEFAULT_EXPANDED,
  ...REVIEWS_SUPER_ADMIN_DEFAULT_EXPANDED,
  ...REPORTS_SUPER_ADMIN_DEFAULT_EXPANDED,
  ...CONFIG_SUPER_ADMIN_DEFAULT_EXPANDED,
};

export const CLIENT_ADMIN_NAV_GROUPS = {
  ...ACCOUNTS_CLIENT_ADMIN_NAV_GROUPS,
  ...TENANT_CLIENT_ADMIN_NAV_GROUPS,
  ...STRUCTURE_CLIENT_ADMIN_NAV_GROUPS,
  ...KPI_CLIENT_ADMIN_NAV_GROUPS,
  ...BILLING_CLIENT_ADMIN_NAV_GROUPS,
  ...REVIEWS_CLIENT_ADMIN_NAV_GROUPS,
  ...REPORTS_CLIENT_ADMIN_NAV_GROUPS,
  ...CONFIG_CLIENT_ADMIN_NAV_GROUPS,
};

export const CLIENT_ADMIN_GROUP_LABELS = {
  ...ACCOUNTS_CLIENT_ADMIN_GROUP_LABELS,
  ...TENANT_CLIENT_ADMIN_GROUP_LABELS,
  ...STRUCTURE_CLIENT_ADMIN_GROUP_LABELS,
  ...KPI_CLIENT_ADMIN_GROUP_LABELS,
  ...BILLING_CLIENT_ADMIN_GROUP_LABELS,
  ...REVIEWS_CLIENT_ADMIN_GROUP_LABELS,
  ...REPORTS_CLIENT_ADMIN_GROUP_LABELS,
  ...CONFIG_CLIENT_ADMIN_GROUP_LABELS,
};

export const CLIENT_ADMIN_DEFAULT_EXPANDED = {
  ...ACCOUNTS_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ...TENANT_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ...STRUCTURE_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ...KPI_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ...BILLING_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ...REVIEWS_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ...REPORTS_CLIENT_ADMIN_DEFAULT_EXPANDED,
  ...CONFIG_CLIENT_ADMIN_DEFAULT_EXPANDED,
};

export const EXECUTIVE_NAV_GROUPS = {
  ...ACCOUNTS_EXECUTIVE_NAV_GROUPS,
  ...STRUCTURE_EXECUTIVE_NAV_GROUPS,
  ...KPI_EXECUTIVE_NAV_GROUPS,
  ...REVIEWS_EXECUTIVE_NAV_GROUPS,
  ...REPORTS_EXECUTIVE_NAV_GROUPS,
};
export const EXECUTIVE_GROUP_LABELS = {
  ...ACCOUNTS_EXECUTIVE_GROUP_LABELS,
  ...STRUCTURE_EXECUTIVE_GROUP_LABELS,
  ...KPI_EXECUTIVE_GROUP_LABELS,
  ...REVIEWS_EXECUTIVE_GROUP_LABELS,
  ...REPORTS_EXECUTIVE_GROUP_LABELS,
};
export const EXECUTIVE_DEFAULT_EXPANDED = {
  ...ACCOUNTS_EXECUTIVE_DEFAULT_EXPANDED,
  ...STRUCTURE_EXECUTIVE_DEFAULT_EXPANDED,
  ...KPI_EXECUTIVE_DEFAULT_EXPANDED,
  ...REVIEWS_EXECUTIVE_DEFAULT_EXPANDED,
  ...REPORTS_EXECUTIVE_DEFAULT_EXPANDED,
};

export const MANAGER_NAV_GROUPS = {
  ...ACCOUNTS_MANAGER_NAV_GROUPS,
  ...STRUCTURE_MANAGER_NAV_GROUPS,
  ...KPI_MANAGER_NAV_GROUPS,
  ...REVIEWS_MANAGER_NAV_GROUPS,
  ...REPORTS_MANAGER_NAV_GROUPS,
};
export const MANAGER_GROUP_LABELS = {
  ...ACCOUNTS_MANAGER_GROUP_LABELS,
  ...STRUCTURE_MANAGER_GROUP_LABELS,
  ...KPI_MANAGER_GROUP_LABELS,
  ...REVIEWS_MANAGER_GROUP_LABELS,
  ...REPORTS_MANAGER_GROUP_LABELS,
};
export const MANAGER_DEFAULT_EXPANDED = {
  ...ACCOUNTS_MANAGER_DEFAULT_EXPANDED,
  ...STRUCTURE_MANAGER_DEFAULT_EXPANDED,
  ...KPI_MANAGER_DEFAULT_EXPANDED,
  ...REVIEWS_MANAGER_DEFAULT_EXPANDED,
  ...REPORTS_MANAGER_DEFAULT_EXPANDED,
};

export const STAFF_NAV_GROUPS = {
  ...ACCOUNTS_STAFF_NAV_GROUPS,
  ...STRUCTURE_STAFF_NAV_GROUPS,
  ...KPI_STAFF_NAV_GROUPS,
  ...REVIEWS_STAFF_NAV_GROUPS,
  ...REPORTS_STAFF_NAV_GROUPS,
};
export const STAFF_GROUP_LABELS = {
  ...ACCOUNTS_STAFF_GROUP_LABELS,
  ...STRUCTURE_STAFF_GROUP_LABELS,
  ...KPI_STAFF_GROUP_LABELS,
  ...REVIEWS_STAFF_GROUP_LABELS,
  ...REPORTS_STAFF_GROUP_LABELS,
};
export const STAFF_DEFAULT_EXPANDED = {
  ...ACCOUNTS_STAFF_DEFAULT_EXPANDED,
  ...STRUCTURE_STAFF_DEFAULT_EXPANDED,
  ...KPI_STAFF_DEFAULT_EXPANDED,
  ...REVIEWS_STAFF_DEFAULT_EXPANDED,
  ...REPORTS_STAFF_DEFAULT_EXPANDED,
};

export const CHAMPION_NAV_GROUPS = {
  ...ACCOUNTS_CHAMPION_NAV_GROUPS,
  ...STRUCTURE_CHAMPION_NAV_GROUPS,
  ...KPI_CHAMPION_NAV_GROUPS,
  ...REVIEWS_CHAMPION_NAV_GROUPS,
  ...REPORTS_CHAMPION_NAV_GROUPS,
};
export const CHAMPION_GROUP_LABELS = {
  ...ACCOUNTS_CHAMPION_GROUP_LABELS,
  ...STRUCTURE_CHAMPION_GROUP_LABELS,
  ...KPI_CHAMPION_GROUP_LABELS,
  ...REVIEWS_CHAMPION_GROUP_LABELS,
  ...REPORTS_CHAMPION_GROUP_LABELS,
};
export const CHAMPION_DEFAULT_EXPANDED = {
  ...ACCOUNTS_CHAMPION_DEFAULT_EXPANDED,
  ...STRUCTURE_CHAMPION_DEFAULT_EXPANDED,
  ...KPI_CHAMPION_DEFAULT_EXPANDED,
  ...REVIEWS_CHAMPION_DEFAULT_EXPANDED,
  ...REPORTS_CHAMPION_DEFAULT_EXPANDED,
};

export const READ_ONLY_NAV_GROUPS = {
  ...ACCOUNTS_READ_ONLY_NAV_GROUPS,
  ...STRUCTURE_READ_ONLY_NAV_GROUPS,
  ...KPI_READ_ONLY_NAV_GROUPS,
  ...REVIEWS_READ_ONLY_NAV_GROUPS,
  ...REPORTS_READ_ONLY_NAV_GROUPS,
};
export const READ_ONLY_GROUP_LABELS = {
  ...ACCOUNTS_READ_ONLY_GROUP_LABELS,
  ...STRUCTURE_READ_ONLY_GROUP_LABELS,
  ...KPI_READ_ONLY_GROUP_LABELS,
  ...REVIEWS_READ_ONLY_GROUP_LABELS,
  ...REPORTS_READ_ONLY_GROUP_LABELS,
};
export const READ_ONLY_DEFAULT_EXPANDED = {
  ...ACCOUNTS_READ_ONLY_DEFAULT_EXPANDED,
  ...STRUCTURE_READ_ONLY_DEFAULT_EXPANDED,
  ...KPI_READ_ONLY_DEFAULT_EXPANDED,
  ...REVIEWS_READ_ONLY_DEFAULT_EXPANDED,
  ...REPORTS_READ_ONLY_DEFAULT_EXPANDED,
};

export default {
  SUPER_ADMIN_NAV_GROUPS,
  SUPER_ADMIN_GROUP_LABELS,
  SUPER_ADMIN_DEFAULT_EXPANDED,
  CLIENT_ADMIN_NAV_GROUPS,
  CLIENT_ADMIN_GROUP_LABELS,
  CLIENT_ADMIN_DEFAULT_EXPANDED,
  EXECUTIVE_NAV_GROUPS,
  EXECUTIVE_GROUP_LABELS,
  EXECUTIVE_DEFAULT_EXPANDED,
  MANAGER_NAV_GROUPS,
  MANAGER_GROUP_LABELS,
  MANAGER_DEFAULT_EXPANDED,
  STAFF_NAV_GROUPS,
  STAFF_GROUP_LABELS,
  STAFF_DEFAULT_EXPANDED,
  CHAMPION_NAV_GROUPS,
  CHAMPION_GROUP_LABELS,
  CHAMPION_DEFAULT_EXPANDED,
  READ_ONLY_NAV_GROUPS,
  READ_ONLY_GROUP_LABELS,
  READ_ONLY_DEFAULT_EXPANDED,
  isAccountsRouteActive,
  isTenantRouteActive,
  isKpiRouteActive,
  isStructureRouteActive,
  isBillingRouteActive,
  isReviewsRouteActive,
  isReportsRouteActive,
};