version: '3.8'

services:
  backend:
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 512M

  celery_worker:
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  postgres:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
