import { API_ENDPOINTS as CONSTANTS_API_ENDPOINTS } from '../../config/constants';
import { API_BASE_URL } from './constants';

export { API_BASE_URL };

export const KPI_ENDPOINTS = CONSTANTS_API_ENDPOINTS.KPI;
export const FRAMEWORK_ENDPOINTS = CONSTANTS_API_ENDPOINTS.FRAMEWORK;
export const TARGET_ENDPOINTS = CONSTANTS_API_ENDPOINTS.TARGET;
export const ACTUAL_ENDPOINTS = CONSTANTS_API_ENDPOINTS.ACTUAL;
export const SCORE_ENDPOINTS = CONSTANTS_API_ENDPOINTS.SCORE;
export const VALIDATION_ENDPOINTS = CONSTANTS_API_ENDPOINTS.VALIDATION || {}; // Add fallback if not defined
export const DASHBOARD_ENDPOINTS = CONSTANTS_API_ENDPOINTS.DASHBOARD;
export const ANALYTICS_ENDPOINTS = CONSTANTS_API_ENDPOINTS.ANALYTICS;
export const BULK_ENDPOINTS = CONSTANTS_API_ENDPOINTS.BULK;
export const CALCULATION_ENDPOINTS = CONSTANTS_API_ENDPOINTS.CALCULATION;
export const EXPORT_ENDPOINTS = CONSTANTS_API_ENDPOINTS.EXPORT;
export const CASCADE_ENDPOINTS = CONSTANTS_API_ENDPOINTS.CASCADE || {};
export const HISTORY_ENDPOINTS = CONSTANTS_API_ENDPOINTS.HISTORY || {};
export const WEIGHT_ENDPOINTS = CONSTANTS_API_ENDPOINTS.WEIGHT || {};
export const LINKAGE_ENDPOINTS = CONSTANTS_API_ENDPOINTS.LINKAGE || {};
export const DEPENDENCY_ENDPOINTS = CONSTANTS_API_ENDPOINTS.DEPENDENCY || {};

export const API_ENDPOINTS = CONSTANTS_API_ENDPOINTS;

export default API_ENDPOINTS;