apiVersion: v1
kind: Namespace
metadata:
  name: falcon-pms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falcon-config
  namespace: falcon-pms
data:
  DJANGO_ENV: "production"
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DJANGO_ALLOWED_HOSTS: "*"
  DB_HOST: "pgbouncer-service"
  DB_PORT: "6432"
  DB_NAME: "fasc_db"
  DB_USER: "postgres"
  REDIS_URL: "redis://redis-service:6379/0"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/1"
  FRONTEND_URL: "https://falcon.example.com"
  BILLING_CURRENCY: "KES"
---
apiVersion: v1
kind: Secret
metadata:
  name: falcon-secrets
  namespace: falcon-pms
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-prod-key-change-in-production"
  JWT_SIGNING_KEY: "0e4b1a19763843fd0050ea534d3f6ca27870248930efe684cca3932199d87589bba098625eb47ed33ff0b08eedf90741b8fef1fd553f7551dac6afcd1d36d408"
  MFA_ENCRYPTION_KEY: "5D_uoNUQ6JLEdjhr_4q_YHZ7OEs3pXfO1shKkU0dodI="
  DB_PASSWORD: "Dazl2006"
  PAYSTACK_SECRET_KEY: "sk_test_7400c09c4522e332d65cecc290afee0dda124d03"
  PAYSTACK_PUBLIC_KEY: "pk_test_3a7cd5da94bc9d3192f198056aff00e379819403"
  BACKUP_MASTER_ENCRYPTION_KEY: "YOUR_STRONG_32_BYTE_BASE64_KEY_HERE"
