apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: falcon-pms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          ports:
            - containerPort: 6432
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: falcon-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: falcon-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: falcon-config
                  key: DB_NAME
            - name: POOL_MODE
              value: "transaction"
            - name: MAX_CLIENT_CONN
              value: "10000"
            - name: DEFAULT_POOL_SIZE
              value: "150"
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: falcon-pms
spec:
  ports:
    - port: 6432
      targetPort: 6432
  selector:
    app: pgbouncer
  type: ClusterIP
