apiVersion: v1
kind: ConfigMap
metadata:
  name: falcon-config
  namespace: falcon-pms
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DJANGO_ALLOWED_HOSTS: "app.falconpms.com,api.falconpms.com,localhost"
  FRONTEND_URL: "https://app.falconpms.com"
  DB_NAME: "fasc_db"
  DB_HOST: "falcon-pgbouncer"
  DB_PORT: "6432"
  REDIS_URL: "redis://falcon-redis:6379/0"
  CACHE_REDIS_URL: "redis://falcon-redis:6379/2"
  EMAIL_HOST: "smtp.sendgrid.net"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  DEFAULT_FROM_EMAIL: "operations@falconpms.com"
  BACKUP_STORAGE_TYPE: "s3"
  BACKUP_S3_BUCKET: "falcon-pms-backups-prod"
  BACKUP_S3_REGION: "us-east-1"
