apiVersion: v1
kind: Service
metadata:
  name: falcon-frontend-service
  namespace: falcon-pms
  labels:
    app.kubernetes.io/name: falcon-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/name: falcon-frontend
