apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: falcon-backend-pdb
  namespace: falcon-pms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: falcon-backend
