import React from 'react';
import { 
    FiCreditCard, FiDollarSign, FiUsers, FiBarChart2, FiFileText, FiRefreshCw, 
    FiAlertCircle, FiCheckCircle, FiClock, FiXCircle, FiCalendar, FiMail, 
    FiDownload, FiPrinter, FiSettings, FiShield, FiLock, FiEye, FiEyeOff, 
    FiTrash2, FiEdit2, FiPlus, FiSearch, FiFilter, FiMoreVertical, 
    FiChevronLeft, FiChevronRight, FiChevronDown, FiChevronUp, FiHome, FiUser, 
    FiLogOut, FiMenu, FiBell, FiStar, FiHeart, FiShare2, FiBookmark, FiFlag, 
    FiMapPin, FiPhone, FiGlobe, FiServer, FiCloud, FiDatabase, FiCpu, FiCode, 
    FiBox, FiPackage, FiShoppingCart, FiTruck, FiCamera, FiVideo, FiMusic, 
    FiHeadphones, FiMonitor, FiTablet, FiSmartphone, FiCopy, FiClipboard, 
    FiLink, FiExternalLink, FiKey, FiAward, FiTrendingUp, FiTrendingDown
} from 'react-icons/fi';

import { 
    MdCreditCard, MdPayment, MdReceipt, MdHistory, MdAccountBalance, 
    MdAccountBalanceWallet, MdTrendingUp, MdTrendingDown, MdAnalytics, 
    MdAssessment, MdDashboard, MdSettings, MdSecurity, MdVerified, MdWarning, 
    MdError, MdInfo, MdHelp, MdSupport, MdContactSupport, MdEmail, MdPhone, 
    MdLocationOn, MdBusiness, MdPerson, MdPeople, MdGroup, MdSchool, MdWork, 
    MdHome, MdStore, MdShoppingCart, MdFavorite, MdStar, MdStarBorder, 
    MdStarHalf, MdThumbUp, MdThumbDown
} from 'react-icons/md';

import { 
    HiOutlineCreditCard, HiOutlineCurrencyDollar, HiOutlineUserGroup, 
    HiOutlineChartBar, HiOutlineDocumentText, HiOutlineRefresh, 
    HiOutlineExclamation, HiOutlineCheck, HiOutlineClock, HiOutlineX, 
    HiOutlineCalendar, HiOutlineMail, HiOutlineDownload, HiOutlinePrinter, 
    HiOutlineCog, HiOutlineShieldCheck, HiOutlineLockClosed, HiOutlineEye, 
    HiOutlineEyeOff, HiOutlineTrash, HiOutlinePencil, HiOutlinePlus, 
    HiOutlineSearch, HiOutlineFilter, HiOutlineDotsVertical, 
    HiOutlineChevronLeft, HiOutlineChevronRight, HiOutlineChevronDown, 
    HiOutlineChevronUp, HiOutlineHome, HiOutlineUser, HiOutlineLogout, 
    HiOutlineMenu, HiOutlineBell, HiOutlineStar, HiOutlineHeart, HiOutlineShare, 
    HiOutlineBookmark, HiOutlineFlag, HiOutlineLocationMarker, HiOutlinePhone, 
    HiOutlineGlobe, HiOutlineServer, HiOutlineCloud, HiOutlineDatabase, 
    HiOutlineChip, HiOutlineCode
} from 'react-icons/hi';

import { 
    BsCreditCard, BsCash, BsWallet, BsGraphUp, BsGraphDown, BsBarChart, 
    BsPieChart, BsFileText, BsCalendar, BsClock, BsCheckCircle, BsXCircle, 
    BsExclamationTriangle, BsInfoCircle, BsQuestionCircle, BsGear, BsShieldLock, 
    BsLock, BsUnlock, BsEye, BsEyeSlash, BsTrash, BsPencil, BsPlus, BsSearch, 
    BsFilter, BsThreeDotsVertical, BsChevronLeft, BsChevronRight, BsChevronDown, 
    BsChevronUp, BsHouse, BsPerson, BsBoxArrowRight, BsList, BsBell, BsStar, 
    BsHeart, BsShare, BsBookmark, BsFlag, BsGeoAlt, BsTelephone, BsEnvelope, 
    BsGlobe, BsServer, BsCloud, BsDatabase, BsCpu, BsCodeSlash
} from 'react-icons/bs';

import { 
    LuCreditCard, LuDollarSign, LuUsers, LuBarChart, LuFileText, LuRefreshCw, 
    LuAlertCircle, LuCheckCircle, LuClock, LuXCircle, LuCalendar, LuMail, 
    LuDownload, LuPrinter, LuSettings, LuShield, LuLock, LuEye, LuEyeOff, 
    LuTrash2, LuEdit2, LuPlus, LuSearch, LuFilter, LuMoreVertical, 
    LuChevronLeft, LuChevronRight, LuChevronDown, LuChevronUp, LuHome, LuUser, 
    LuLogOut, LuMenu, LuBell, LuStar, LuHeart, LuShare2, LuBookmark, LuFlag, 
    LuMapPin, LuPhone, LuGlobe, LuServer, LuCloud, LuDatabase, LuCpu, LuCode
} from 'react-icons/lu';

export const BillingIcons = {
    // Fi Icons
    CreditCard: FiCreditCard,
    Dollar: FiDollarSign,
    Users: FiUsers,
    Chart: FiBarChart2,
    File: FiFileText,
    Refresh: FiRefreshCw,
    Alert: FiAlertCircle,
    Success: FiCheckCircle,
    Clock: FiClock,
    Close: FiXCircle,
    Calendar: FiCalendar,
    Mail: FiMail,
    Download: FiDownload,
    Print: FiPrinter,
    Settings: FiSettings,
    Shield: FiShield,
    Lock: FiLock,
    Eye: FiEye,
    EyeOff: FiEyeOff,
    Delete: FiTrash2,
    Edit: FiEdit2,
    Add: FiPlus,
    Search: FiSearch,
    Filter: FiFilter,
    More: FiMoreVertical,
    ChevronLeft: FiChevronLeft,
    ChevronRight: FiChevronRight,
    ChevronDown: FiChevronDown,
    ChevronUp: FiChevronUp,
    Home: FiHome,
    User: FiUser,
    Logout: FiLogOut,
    Menu: FiMenu,
    Bell: FiBell,
    Star: FiStar,
    Heart: FiHeart,
    Share: FiShare2,
    Bookmark: FiBookmark,
    Flag: FiFlag,
    MapPin: FiMapPin,
    Phone: FiPhone,
    Globe: FiGlobe,
    Server: FiServer,
    Cloud: FiCloud,
    Database: FiDatabase,
    Cpu: FiCpu,
    Code: FiCode,
    Box: FiBox,
    Package: FiPackage,
    ShoppingCart: FiShoppingCart,
    Truck: FiTruck,
    Camera: FiCamera,
    Video: FiVideo,
    Music: FiMusic,
    Headphones: FiHeadphones,
    Monitor: FiMonitor,
    Tablet: FiTablet,
    Smartphone: FiSmartphone,
    Copy: FiCopy,
    Clipboard: FiClipboard,
    Link: FiLink,
    ExternalLink: FiExternalLink,
    Key: FiKey,
    Award: FiAward,
    TrendingUp: FiTrendingUp,
    TrendingDown: FiTrendingDown,

    // Md Icons
    MdCreditCard: MdCreditCard,
    MdPayment: MdPayment,
    MdReceipt: MdReceipt,
    MdHistory: MdHistory,
    MdAccountBalance: MdAccountBalance,
    MdAccountBalanceWallet: MdAccountBalanceWallet,
    MdTrendingUp: MdTrendingUp,
    MdTrendingDown: MdTrendingDown,
    MdAnalytics: MdAnalytics,
    MdAssessment: MdAssessment,
    MdDashboard: MdDashboard,
    MdSettings: MdSettings,
    MdSecurity: MdSecurity,
    MdVerified: MdVerified,
    MdWarning: MdWarning,
    MdError: MdError,
    MdInfo: MdInfo,
    MdHelp: MdHelp,
    MdSupport: MdSupport,
    MdContactSupport: MdContactSupport,
    MdEmail: MdEmail,
    MdPhone: MdPhone,
    MdLocationOn: MdLocationOn,
    MdBusiness: MdBusiness,
    MdPerson: MdPerson,
    MdPeople: MdPeople,
    MdGroup: MdGroup,
    MdSchool: MdSchool,
    MdWork: MdWork,
    MdHome: MdHome,
    MdStore: MdStore,
    MdShoppingCart: MdShoppingCart,
    MdFavorite: MdFavorite,
    MdStar: MdStar,
    MdStarBorder: MdStarBorder,
    MdStarHalf: MdStarHalf,
    MdThumbUp: MdThumbUp,
    MdThumbDown: MdThumbDown,

    // Hi Icons
    HiCreditCard: HiOutlineCreditCard,
    HiDollar: HiOutlineCurrencyDollar,
    HiUsers: HiOutlineUserGroup,
    HiChart: HiOutlineChartBar,
    HiFile: HiOutlineDocumentText,
    HiRefresh: HiOutlineRefresh,
    HiAlert: HiOutlineExclamation,
    HiCheck: HiOutlineCheck,
    HiClock: HiOutlineClock,
    HiClose: HiOutlineX,
    HiCalendar: HiOutlineCalendar,
    HiMail: HiOutlineMail,
    HiDownload: HiOutlineDownload,
    HiPrint: HiOutlinePrinter,
    HiSettings: HiOutlineCog,
    HiShield: HiOutlineShieldCheck,
    HiLock: HiOutlineLockClosed,
    HiEye: HiOutlineEye,
    HiEyeOff: HiOutlineEyeOff,
    HiDelete: HiOutlineTrash,
    HiEdit: HiOutlinePencil,
    HiAdd: HiOutlinePlus,
    HiSearch: HiOutlineSearch,
    HiFilter: HiOutlineFilter,
    HiMore: HiOutlineDotsVertical,
    HiChevronLeft: HiOutlineChevronLeft,
    HiChevronRight: HiOutlineChevronRight,
    HiChevronDown: HiOutlineChevronDown,
    HiChevronUp: HiOutlineChevronUp,
    HiHome: HiOutlineHome,
    HiUser: HiOutlineUser,
    HiLogout: HiOutlineLogout,
    HiMenu: HiOutlineMenu,
    HiBell: HiOutlineBell,
    HiStar: HiOutlineStar,
    HiHeart: HiOutlineHeart,
    HiShare: HiOutlineShare,
    HiBookmark: HiOutlineBookmark,
    HiFlag: HiOutlineFlag,
    HiMapPin: HiOutlineLocationMarker,
    HiPhone: HiOutlinePhone,
    HiGlobe: HiOutlineGlobe,
    HiServer: HiOutlineServer,
    HiCloud: HiOutlineCloud,
    HiDatabase: HiOutlineDatabase,
    HiCpu: HiOutlineChip,
    HiCode: HiOutlineCode,

    // Bs Icons
    BsCreditCard: BsCreditCard,
    BsCash: BsCash,
    BsWallet: BsWallet,
    BsGraphUp: BsGraphUp,
    BsGraphDown: BsGraphDown,
    BsBarChart: BsBarChart,
    BsPieChart: BsPieChart,
    BsFileText: BsFileText,
    BsCalendar: BsCalendar,
    BsClock: BsClock,
    BsCheckCircle: BsCheckCircle,
    BsXCircle: BsXCircle,
    BsExclamationTriangle: BsExclamationTriangle,
    BsInfoCircle: BsInfoCircle,
    BsQuestionCircle: BsQuestionCircle,
    BsGear: BsGear,
    BsShieldLock: BsShieldLock,
    BsLock: BsLock,
    BsUnlock: BsUnlock,
    BsEye: BsEye,
    BsEyeSlash: BsEyeSlash,
    BsTrash: BsTrash,
    BsPencil: BsPencil,
    BsPlus: BsPlus,
    BsSearch: BsSearch,
    BsFilter: BsFilter,
    BsThreeDotsVertical: BsThreeDotsVertical,
    BsChevronLeft: BsChevronLeft,
    BsChevronRight: BsChevronRight,
    BsChevronDown: BsChevronDown,
    BsChevronUp: BsChevronUp,
    BsHouse: BsHouse,
    BsPerson: BsPerson,
    BsBoxArrowRight: BsBoxArrowRight,
    BsList: BsList,
    BsBell: BsBell,
    BsStar: BsStar,
    BsHeart: BsHeart,
    BsShare: BsShare,
    BsBookmark: BsBookmark,
    BsFlag: BsFlag,
    BsGeoAlt: BsGeoAlt,
    BsTelephone: BsTelephone,
    BsEnvelope: BsEnvelope,
    BsGlobe: BsGlobe,
    BsServer: BsServer,
    BsCloud: BsCloud,
    BsDatabase: BsDatabase,
    BsCpu: BsCpu,
    BsCodeSlash: BsCodeSlash,

    // Lu Icons
    LuCreditCard: LuCreditCard,
    LuDollar: LuDollarSign,
    LuUsers: LuUsers,
    LuFile: LuFileText,
    LuRefresh: LuRefreshCw,
    LuClock: LuClock,
    LuCalendar: LuCalendar,
    LuMail: LuMail,
    LuDownload: LuDownload,
    LuPrint: LuPrinter,
    LuSettings: LuSettings,
    LuShield: LuShield,
    LuLock: LuLock,
    LuEye: LuEye,
    LuEyeOff: LuEyeOff,
    LuDelete: LuTrash2,
    LuAdd: LuPlus,
    LuSearch: LuSearch,
    LuFilter: LuFilter,
    LuChevronLeft: LuChevronLeft,
    LuChevronRight: LuChevronRight,
    LuChevronDown: LuChevronDown,
    LuChevronUp: LuChevronUp,
    LuUser: LuUser,
    LuLogout: LuLogOut,
    LuMenu: LuMenu,
    LuBell: LuBell,
    LuStar: LuStar,
    LuHeart: LuHeart,
    LuShare: LuShare2,
    LuBookmark: LuBookmark,
    LuFlag: LuFlag,
    LuMapPin: LuMapPin,
    LuPhone: LuPhone,
    LuGlobe: LuGlobe,
    LuServer: LuServer,
    LuCloud: LuCloud,
    LuDatabase: LuDatabase,
    LuCpu: LuCpu,
    LuCode: LuCode,
};

export default BillingIcons;