import React from 'react';
import {
    FiActivity,
    FiAlertCircle,
    FiAlertTriangle,
    FiArrowDownRight,
    FiArrowUpRight,
    FiBarChart2,
    FiCheck,
    FiCheckCircle,
    FiCircle,
    FiClipboard,
    FiClock,
    FiCreditCard,
    FiDollarSign,
    FiDownload,
    FiEdit,
    FiFileText,
    FiInfo,
    FiLock,
    FiRefreshCcw,
    FiRepeat,
    FiSettings,
    FiSearch,
    FiStar,
    FiTrendingDown,
    FiTrendingUp,
    FiUsers,
    FiX,
    FiXCircle,
    FiZap,
} from 'react-icons/fi';

const ICONS = {
    overview: FiBarChart2,
    dashboard: FiBarChart2,
    totalRevenue: FiDollarSign,
    activeSubscriptions: FiUsers,
    revenuePerUser: FiTrendingUp,
    paymentSuccessRate: FiCheckCircle,
    paymentMethods: FiCreditCard,
    invoices: FiFileText,
    settings: FiSettings,
    subscriptions: FiRefreshCcw,
    transactions: FiCreditCard,
    refunds: FiRepeat,
    webhooks: FiZap,
    analytics: FiTrendingUp,
    tenants: FiUsers,
    reports: FiBarChart2,
    defaultBadge: FiStar,
    warning: FiAlertTriangle,
    info: FiInfo,
    success: FiCheckCircle,
    failed: FiXCircle,
    pending: FiClock,
    refunded: FiRepeat,
    disputed: FiAlertTriangle,
    cancelled: FiX,
    expired: FiClock,
    pending_cancellation: FiRefreshCcw,
    draft: FiFileText,
    invoiceDownload: FiDownload,
    invoicePay: FiDollarSign,
    invoiceSearch: FiSearch,
    card: FiCreditCard,
    event: FiActivity,
    chargeSuccess: FiDollarSign,
    chargeDispute: FiAlertTriangle,
    subscriptionCreate: FiRefreshCcw,
    subscriptionDisable: FiX,
    subscriptionEnable: FiCheck,
    invoiceCreate: FiFileText,
    invoiceUpdate: FiEdit,
    invoicePaymentFailed: FiXCircle,
    totalEvents: FiActivity,
    processed: FiCheck,
    failedStat: FiX,
    plan: FiClipboard,
    unlimited: FiCircle,
    upgrade: FiArrowUpRight,
    downgrade: FiArrowDownRight,
    renewal: FiRepeat,
    refund: FiRepeat,
    lock: FiLock,
    noPaymentMethods: FiCreditCard,
    noInvoices: FiFileText,
    noTransactions: FiCreditCard,
    modalWarning: FiAlertTriangle,
    cardPreview: FiCreditCard,
};

export const BillingIcons = ICONS;

export const renderBillingIcon = (name, props = { size: 18 }) => {
    const Icon = ICONS[name];
    return Icon ? <Icon {...props} /> : null;
};
