task_routes_dict = {
    'apps.accounts.tasks.send_*': {'queue': 'email'},
    'apps.accounts.tasks.cleanup_*': {'queue': 'cleanup'},
    'apps.accounts.tasks.unlock_*': {'queue': 'cleanup'},
    'apps.accounts.tasks.remind_*': {'queue': 'email'},
    'apps.accounts.tasks.check_*': {'queue': 'cleanup'},
    'apps.kpi.tasks.calculations.calculate_*': {'queue': 'calculations'},
    'apps.kpi.tasks.calculations.update_traffic_light_task': {'queue': 'calculations'},
    'apps.kpi.tasks.aggregates.update_aggregated_scores_task': {'queue': 'aggregation'},
    'apps.kpi.tasks.aggregates.refresh_materialized_views_task': {'queue': 'analytics'},
    'apps.kpi.tasks.aggregates.precompute_dashboard_cache_task': {'queue': 'dashboard'},
    'apps.kpi.tasks.notifications.send_*': {'queue': 'notifications'},
    'apps.kpi.tasks.notifications.*_reminder_task': {'queue': 'notifications'},
    'apps.kpi.tasks.alerts.*_alert_task': {'queue': 'notifications'},
    'apps.kpi.tasks.alerts.send_*': {'queue': 'notifications'},
    'apps.kpi.tasks.email_tasks.send_*_email_task': {'queue': 'email'},
    'apps.kpi.tasks.cleanup.cleanup_*': {'queue': 'cleanup'},
    'apps.kpi.tasks.cascade.cascade_*': {'queue': 'cascade'},
    'apps.reviews.tasks.batch_*': {'queue': 'reviews_batch'},
    'apps.reviews.tasks.*_reminder*': {'queue': 'reviews_notifications'},
    'apps.reviews.tasks.send_*': {'queue': 'reviews_notifications'},
    'apps.reviews.tasks.*_deadline*': {'queue': 'reviews_deadlines'},
    'apps.reviews.tasks.*_calibration*': {'queue': 'reviews_calibration'},
    'apps.reviews.tasks.*_feedback*': {'queue': 'reviews_feedback'},
    'apps.reviews.tasks.*_pip*': {'queue': 'reviews_pip'},
    'apps.reviews.tasks.cleanup_*': {'queue': 'reviews_cleanup'},
    'apps.reviews.tasks.*_report*': {'queue': 'reviews_reports'},
    'apps.reviews.tasks.*_aggregat*': {'queue': 'reviews_aggregation'},
    'apps.reviews.tasks.sync_*': {'queue': 'reviews_aggregation'},
    'apps.reviews.tasks.calculate_*': {'queue': 'reviews_aggregation'},
    'apps.reviews.tasks.warm_*': {'queue': 'reviews_default'},
    'apps.reviews.tasks.health_*': {'queue': 'reviews_default'},
    'apps.reviews.tasks.*': {'queue': 'reviews_default'},
    'billing.tasks.process_due_renewals': {'queue': 'billing'},
    'billing.tasks.process_expired_trials': {'queue': 'billing'},
    'billing.tasks.apply_pending_plan_changes': {'queue': 'billing'},
    'billing.tasks.sync_paystack_transactions': {'queue': 'billing'},
    'billing.tasks.generate_invoice_pdf': {'queue': 'billing'},
    'billing.tasks.store_invoice_pdf': {'queue': 'billing'},
    'billing.tasks.send_renewal_reminders': {'queue': 'notifications'},
    'billing.tasks.send_invoice_emails': {'queue': 'notifications'},
    'billing.tasks.send_payment_confirmation': {'queue': 'notifications'},
    'billing.tasks.process_webhook': {'queue': 'webhooks'},
    'billing.tasks.retry_failed_webhooks': {'queue': 'webhooks'},
    'billing.tasks.cleanup_*': {'queue': 'cleanup'},
    'apps.configs.tasks.execute_backup_task': {'queue': 'backup'},
    'apps.configs.tasks.apply_retention_policies_task': {'queue': 'maintenance'},
    'apps.configs.tasks.verify_backups_task': {'queue': 'backup'},
    'apps.configs.tasks.risk_based_maintenance_task': {'queue': 'maintenance'},
    'apps.configs.tasks.health_check_all_apps_task': {'queue': 'health_check'},
    'apps.configs.tasks.conditional_maintenance_trigger_task': {'queue': 'maintenance'},
    'apps.configs.tasks.execute_due_schedules_task': {'queue': 'scheduler'},
    'apps.configs.tasks.cleanup_old_artifacts_task': {'queue': 'maintenance'},
    'apps.configs.tasks.sync_dr_metrics_task': {'queue': 'analytics'},
    'apps.configs.tasks.disaster_recovery_drill_task': {'queue': 'dr'},
    'apps.configs.tasks.restore_*': {'queue': 'restore'},
    'apps.configs.tasks.backup_*': {'queue': 'backup'},
    'apps.configs.tasks.dr_*': {'queue': 'dr'},
    'structure.tasks.*': {'queue': 'structure'},
    'structure.tasks.export_*': {'queue': 'export'},
    'structure.tasks.warm_*': {'queue': 'cache'},
    'structure.tasks.cache_*': {'queue': 'cache'},
    'apps.dashboard.tasks.warm_*': {'queue': 'dashboard'},
    'apps.dashboard.tasks.warm_all_tenant_dashboards': {'queue': 'dashboard'},
    'apps.dashboard.tasks.rebuild_org_tree_cache': {'queue': 'dashboard'},
    'apps.dashboard.tasks.precompute_widget_data': {'queue': 'dashboard'},
    'apps.dashboard.tasks.sync_*': {'queue': 'dashboard'},
    'apps.dashboard.tasks.aggregate_dashboard_metrics': {'queue': 'aggregation'},
    'apps.dashboard.tasks.calculate_*': {'queue': 'aggregation'},
    'apps.dashboard.tasks.compute_*': {'queue': 'aggregation'},
    'apps.dashboard.tasks.process_due_exports': {'queue': 'export'},
    'apps.dashboard.tasks.process_user_exports': {'queue': 'export'},
    'apps.dashboard.tasks.export_*': {'queue': 'export'},
    'apps.dashboard.tasks.generate_monthly_reports': {'queue': 'export_high'},
    'apps.dashboard.tasks.generate_quarterly_reports': {'queue': 'export_high'},
    'apps.dashboard.tasks.clean_expired_exports': {'queue': 'cleanup'},
    'apps.dashboard.tasks.cleanup_old_audit_logs': {'queue': 'cleanup'},
    'apps.dashboard.tasks.archive_old_dashboard_data': {'queue': 'cleanup'},
    'apps.dashboard.tasks.clear_stale_cache': {'queue': 'cleanup'},
    'apps.dashboard.tasks.check_alerts': {'queue': 'notifications'},
    'apps.dashboard.tasks.send_daily_digest': {'queue': 'email'},
    'apps.dashboard.tasks.send_weekly_digest': {'queue': 'email'},
    'apps.dashboard.tasks.send_user_alerts': {'queue': 'notifications'},
    'apps.dashboard.tasks.check_missing_data': {'queue': 'notifications'},
    'apps.dashboard.tasks.alert_*': {'queue': 'notifications'},
    'apps.dashboard.tasks.refresh_tenant_snapshots': {'queue': 'analytics'},
    'apps.dashboard.tasks.refresh_executive_snapshots': {'queue': 'analytics'},
    'apps.dashboard.tasks.snapshot_*': {'queue': 'analytics'},
    'apps.dashboard.tasks.health_check': {'queue': 'health_check'},
    'apps.dashboard.tasks.health_*': {'queue': 'health_check'},
    'apps.dashboard.tasks.user_*': {'queue': 'dashboard'},
    'apps.dashboard.tasks.refresh_*': {'queue': 'dashboard'},
    'apps.dashboard.tasks.realtime_*': {'queue': 'realtime'},
    'apps.dashboard.tasks.websocket_*': {'queue': 'realtime'},
    'notifications.tasks.*': {'queue': 'notification'},
    'priority.*': {'queue': 'priority'},
}

def route_tasks(name, args, kwargs, options, task=None, **kw):
    if name.startswith('structure.tasks.'):
        if 'export' in name:
            return {'queue': 'export'}
        elif 'cache' in name or 'warm' in name:
            return {'queue': 'cache'}
        return {'queue': 'structure'}
    elif name.startswith('notifications.tasks.'):
        return {'queue': 'notification'}
    elif name.startswith('priority.'):
        return {'queue': 'priority'}
    elif name.startswith('apps.reviews.tasks.'):
        if 'report' in name:
            return {'queue': 'reviews_reports'}
        elif 'aggregat' in name or 'sync' in name or 'calculate' in name:
            return {'queue': 'reviews_aggregation'}
    return None

task_routes = ([task_routes_dict, route_tasks])