from celery.schedules import crontab

beat_schedule = {
    'cleanup-expired-sessions': {'task': 'accounts.cleanup_expired_sessions', 'schedule': crontab(minute=0, hour='*/1'), 'options': {'expires': 3600}},
    'cleanup-expired-blacklist': {'task': 'accounts.cleanup_expired_blacklist', 'schedule': crontab(minute=0, hour=0), 'options': {'expires': 86400}},
    'cleanup-old-audit-logs': {'task': 'accounts.cleanup_old_audit_logs', 'schedule': crontab(minute=0, hour=2, day_of_month=1), 'options': {'expires': 86400}, 'kwargs': {'retention_days': 365}},
    'cleanup-old-login-attempts': {'task': 'accounts.cleanup_old_login_attempts', 'schedule': crontab(minute=0, hour=3, day_of_week=0), 'options': {'expires': 86400}, 'kwargs': {'retention_days': 90}},
    'unlock-locked-accounts': {'task': 'accounts.unlock_locked_accounts', 'schedule': crontab(minute='*/15'), 'options': {'expires': 900}},
    'remind-inactive-users': {'task': 'accounts.remind_inactive_users', 'schedule': crontab(minute=0, hour=9, day_of_week=1), 'options': {'expires': 86400}, 'kwargs': {'days_inactive': 30}},
    'check-password-expiry': {'task': 'accounts.check_password_expiry', 'schedule': crontab(minute=0, hour=8), 'options': {'expires': 86400}, 'kwargs': {'expiry_days': 90}},
    'calculate-scores-daily': {'task': 'apps.kpi.tasks.schedules.scheduled_calculation_task', 'schedule': crontab(hour=2, minute=0), 'options': {'expires': 3600}},
    'send-missing-data-reminders': {'task': 'apps.kpi.tasks.schedules.scheduled_reminder_task', 'schedule': crontab(day_of_month=5, hour=8, minute=0), 'options': {'expires': 86400}},
    'check-red-alerts': {'task': 'apps.kpi.tasks.schedules.scheduled_red_alert_task', 'schedule': crontab(hour=9, minute=0), 'options': {'expires': 3600}},
    'refresh-materialized-views': {'task': 'apps.kpi.tasks.dashboard.refresh_materialized_views_task', 'schedule': crontab(minute=0), 'options': {'expires': 3600}},
    'precompute-dashboard-cache': {'task': 'apps.kpi.tasks.dashboard.precompute_dashboard_cache_task', 'schedule': crontab(hour=3, minute=0), 'options': {'expires': 7200}},
    'cleanup-calculation-logs': {'task': 'apps.kpi.tasks.cleanup.cleanup_old_calculation_logs_task', 'schedule': crontab(day_of_week=0, hour=2, minute=0), 'args': [30], 'options': {'expires': 86400}},
    'cleanup-expired-cache': {'task': 'apps.kpi.tasks.cleanup.cleanup_expired_cache_task', 'schedule': crontab(hour=4, minute=0), 'options': {'expires': 3600}},
    'check-pending-validations': {'task': 'apps.kpi.tasks.notifications.send_validation_notification_task', 'schedule': crontab(minute=0, hour='*/2'), 'options': {'expires': 3600}},
    'check-threshold-breaches': {'task': 'apps.kpi.tasks.notifications.send_threshold_breach_alerts_task', 'schedule': crontab(hour=10, minute=0), 'options': {'expires': 3600}},
    'daily-database-backup': {'task': 'apps.kpi.tasks.backup.daily_backup_task', 'schedule': crontab(hour=1, minute=0), 'args': [{'type': 'database'}]},
    'daily-media-backup': {'task': 'apps.kpi.tasks.backup.daily_backup_task', 'schedule': crontab(hour=2, minute=0), 'args': [{'type': 'media'}]},
    'weekly-full-backup': {'task': 'apps.kpi.tasks.backup.full_backup_task', 'schedule': crontab(day_of_week=0, hour=3, minute=0)},
    'monthly-archive': {'task': 'apps.kpi.tasks.backup.archive_backup_task', 'schedule': crontab(day_of_month=1, hour=4, minute=0)},
    'cleanup-old-backups': {'task': 'apps.kpi.tasks.backup.cleanup_old_backups_task', 'schedule': crontab(day_of_month=1, hour=5, minute=0), 'args': [30]},
    'warm-structure-cache-daily': {'task': 'structure.tasks.warm_structure_cache', 'schedule': crontab(hour=3, minute=0), 'args': []},
    'refresh-materialized-views-hourly': {'task': 'structure.tasks.refresh_materialized_views', 'schedule': crontab(minute=0), 'args': []},
    'detect-orphaned-nodes-daily': {'task': 'structure.tasks.detect_orphaned_nodes', 'schedule': crontab(hour=2, minute=30), 'args': []},
    'validate-org-integrity-daily': {'task': 'structure.tasks.validate_org_integrity', 'schedule': crontab(hour=4, minute=0), 'args': []},
    'detect-circular-references-daily': {'task': 'structure.tasks.detect_circular_references', 'schedule': crontab(hour=4, minute=30), 'args': []},
    'cleanup-orphaned-versions-weekly': {'task': 'structure.tasks.cleanup_orphaned_versions', 'schedule': crontab(day_of_week=0, hour=5, minute=0), 'args': []},
    'rebuild-hierarchy-indexes-monthly': {'task': 'structure.tasks.rebuild_hierarchy_indexes', 'schedule': crontab(day_of_month=1, hour=6, minute=0), 'args': []},
    'process-due-renewals': {'task': 'billing.tasks.process_due_renewals', 'schedule': crontab(hour=2, minute=0), 'options': {'queue': 'billing'}},
    'process-expired-trials': {'task': 'billing.tasks.process_expired_trials', 'schedule': crontab(hour=3, minute=0), 'options': {'queue': 'billing'}},
    'send-renewal-reminders': {'task': 'billing.tasks.send_renewal_reminders', 'schedule': crontab(hour=9, minute=0), 'options': {'queue': 'notifications'}},
    'apply-pending-plan-changes': {'task': 'billing.tasks.apply_pending_plan_changes', 'schedule': crontab(hour=1, minute=0), 'options': {'queue': 'billing'}},
    'send-invoice-emails': {'task': 'billing.tasks.send_invoice_emails', 'schedule': crontab(hour=10, minute=0), 'options': {'queue': 'notifications'}},
    'retry-failed-webhooks': {'task': 'billing.tasks.retry_failed_webhooks', 'schedule': crontab(minute='*/30'), 'options': {'queue': 'webhooks'}},
    'cleanup-expired-webhooks': {'task': 'billing.tasks.cleanup_expired_webhooks', 'schedule': crontab(day_of_month=1, hour=0, minute=0), 'options': {'queue': 'cleanup'}},
    'sync-paystack-transactions': {'task': 'billing.tasks.sync_paystack_transactions', 'schedule': crontab(hour=5, minute=0), 'options': {'queue': 'billing'}},
    'health-check-all-apps': {'task': 'apps.configs.tasks.health_check_all_apps_task', 'schedule': crontab(minute='*/5'), 'options': {'queue': 'health_check', 'expires': 300}},
    'apply-retention-policies': {'task': 'apps.configs.tasks.apply_retention_policies_task', 'schedule': crontab(hour=2, minute=0), 'options': {'queue': 'maintenance', 'expires': 3600}},
    'verify-backups': {'task': 'apps.configs.tasks.verify_backups_task', 'schedule': crontab(hour=3, minute=30), 'options': {'queue': 'backup', 'expires': 7200}},
    'risk-based-maintenance': {'task': 'apps.configs.tasks.risk_based_maintenance_task', 'schedule': crontab(hour='*/6', minute=15), 'options': {'queue': 'maintenance', 'expires': 1800}},
    'conditional-maintenance-trigger': {'task': 'apps.configs.tasks.conditional_maintenance_trigger_task', 'schedule': crontab(minute='*/10'), 'options': {'queue': 'maintenance', 'expires': 600}},
    'execute-due-schedules': {'task': 'apps.configs.tasks.execute_due_schedules_task', 'schedule': crontab(minute='*'), 'options': {'queue': 'scheduler', 'expires': 60}},
    'cleanup-old-artifacts': {'task': 'apps.configs.tasks.cleanup_old_artifacts_task', 'schedule': crontab(hour=1, minute=0, day_of_month='1'), 'options': {'queue': 'maintenance', 'expires': 86400}},
    'sync-dr-metrics': {'task': 'apps.configs.tasks.sync_dr_metrics_task', 'schedule': crontab(hour=0, minute=0), 'options': {'queue': 'analytics', 'expires': 3600}},
    'weekly-dr-drill': {'task': 'apps.configs.tasks.disaster_recovery_drill_task', 'schedule': crontab(day_of_week='saturday', hour=2, minute=0), 'options': {'queue': 'dr', 'expires': 14400}, 'kwargs': {'plan_id': None}},
    'reviews-check-cycle-deadlines': {'task': 'apps.reviews.tasks.check_cycle_deadlines', 'schedule': crontab(hour=9, minute=0), 'options': {'expires': 3600}},
    'reviews-close-expired-cycles': {'task': 'apps.reviews.tasks.close_expired_cycles', 'schedule': crontab(hour=1, minute=0), 'options': {'expires': 7200}},
    'reviews-batch-create-self-assessments': {'task': 'apps.reviews.tasks.batch_create_self_assessments', 'schedule': crontab(hour=0, minute=30), 'options': {'expires': 3600}},
    'reviews-batch-generate-final-ratings': {'task': 'apps.reviews.tasks.batch_generate_final_ratings', 'schedule': crontab(hour=3, minute=0), 'options': {'expires': 10800}},
    'reviews-check-pip-deadlines': {'task': 'apps.reviews.tasks.check_pip_deadlines', 'schedule': crontab(hour=10, minute=0), 'options': {'expires': 3600}},
    'reviews-check-pip-action-deadlines': {'task': 'apps.reviews.tasks.check_pip_action_deadlines', 'schedule': crontab(hour=10, minute=30), 'options': {'expires': 3600}},
    'reviews-auto-escalate-pips': {'task': 'apps.reviews.tasks.auto_escalate_pip', 'schedule': crontab(hour=0, minute=15), 'options': {'expires': 7200}},
    'reviews-detect-stalled-pips': {'task': 'apps.reviews.tasks.detect_stalled_pips', 'schedule': crontab(day_of_week=1, hour=8, minute=0), 'options': {'expires': 86400}, 'kwargs': {'stalled_days': 14}},
    'reviews-send-feedback-reminders': {'task': 'apps.reviews.tasks.send_feedback_reminders', 'schedule': crontab(hour=11, minute=0), 'options': {'expires': 3600}},
    'reviews-batch-generate-feedback-summaries': {'task': 'apps.reviews.tasks.batch_generate_feedback_summaries', 'schedule': crontab(hour=2, minute=0), 'options': {'expires': 7200}},
    'reviews-escalate-unanswered-feedback': {'task': 'apps.reviews.tasks.escalate_unanswered_feedback', 'schedule': crontab(day_of_week=3, hour=9, minute=0), 'options': {'expires': 86400}, 'kwargs': {'overdue_days': 7}},
    'reviews-send-calibration-reminders': {'task': 'apps.reviews.tasks.send_calibration_reminders', 'schedule': crontab(hour=9, minute=30), 'options': {'expires': 3600}},
    'reviews-calibration-followup': {'task': 'apps.reviews.tasks.calibration_followup', 'schedule': crontab(hour=14, minute=0, day_of_week=4), 'options': {'expires': 86400}, 'kwargs': {'days_since_session': 3}},
    'reviews-self-assessment-reminder': {'task': 'apps.reviews.tasks.send_self_assessment_reminders', 'schedule': crontab(minute=0, hour='*/6'), 'options': {'expires': 3600}},
    'reviews-supervisor-review-reminder': {'task': 'apps.reviews.tasks.send_supervisor_review_reminders', 'schedule': crontab(minute=0, hour='*/4'), 'options': {'expires': 3600}},
    'reviews-cleanup-old-comments': {'task': 'apps.reviews.tasks.cleanup_old_comments', 'schedule': crontab(day_of_week=0, hour=2, minute=0), 'options': {'expires': 86400}, 'kwargs': {'days': 90}},
    'reviews-archive-completed-cycles': {'task': 'apps.reviews.tasks.archive_completed_cycles', 'schedule': crontab(day_of_month=1, hour=3, minute=0), 'options': {'expires': 86400}, 'kwargs': {'archive_days': 365}},
    'reviews-cleanup-orphaned-ratings': {'task': 'apps.reviews.tasks.cleanup_orphaned_ratings', 'schedule': crontab(hour=4, minute=30, day_of_week=0), 'options': {'expires': 86400}},
    'reviews-validate-data-integrity': {'task': 'apps.reviews.tasks.validate_data_integrity', 'schedule': crontab(day_of_month=15, hour=5, minute=0), 'options': {'expires': 86400}},
    'reviews-generate-monthly-report': {'task': 'apps.reviews.tasks.generate_monthly_report', 'schedule': crontab(day_of_month=1, hour=6, minute=0), 'options': {'expires': 86400}, 'kwargs': {'report_type': 'monthly'}},
    'reviews-generate-quarterly-report-q1': {'task': 'apps.reviews.tasks.generate_quarterly_report', 'schedule': crontab(day_of_month=1, month_of_year=1, hour=7, minute=0), 'options': {'expires': 86400}, 'kwargs': {'report_type': 'quarterly', 'quarter': 1}},
    'reviews-generate-quarterly-report-q2': {'task': 'apps.reviews.tasks.generate_quarterly_report', 'schedule': crontab(day_of_month=1, month_of_year=4, hour=7, minute=0), 'options': {'expires': 86400}, 'kwargs': {'report_type': 'quarterly', 'quarter': 2}},
    'reviews-generate-quarterly-report-q3': {'task': 'apps.reviews.tasks.generate_quarterly_report', 'schedule': crontab(day_of_month=1, month_of_year=7, hour=7, minute=0), 'options': {'expires': 86400}, 'kwargs': {'report_type': 'quarterly', 'quarter': 3}},
    'reviews-generate-quarterly-report-q4': {'task': 'apps.reviews.tasks.generate_quarterly_report', 'schedule': crontab(day_of_month=1, month_of_year=10, hour=7, minute=0), 'options': {'expires': 86400}, 'kwargs': {'report_type': 'quarterly', 'quarter': 4}},
    'reviews-calculate-rating-distribution': {'task': 'apps.reviews.tasks.calculate_rating_distribution', 'schedule': crontab(hour=1, minute=30, day_of_week=0), 'options': {'expires': 7200}},
    'reviews-detect-rating-inflation': {'task': 'apps.reviews.tasks.detect_rating_inflation', 'schedule': crontab(day_of_month=1, hour=4, minute=0), 'options': {'expires': 86400}, 'kwargs': {'threshold_percentage': 15}},
    'reviews-calculate-manager-consistency': {'task': 'apps.reviews.tasks.calculate_manager_consistency', 'schedule': crontab(day_of_week=1, hour=5, minute=0), 'options': {'expires': 86400}},
    'reviews-sync-kpi-data': {'task': 'apps.reviews.tasks.sync_kpi_data', 'schedule': crontab(minute=0, hour='*/2'), 'options': {'expires': 3600}},
    'reviews-sync-mission-data': {'task': 'apps.reviews.tasks.sync_mission_data', 'schedule': crontab(hour=1, minute=0), 'options': {'expires': 7200}},
    'reviews-sync-task-data': {'task': 'apps.reviews.tasks.sync_task_data', 'schedule': crontab(hour=1, minute=30), 'options': {'expires': 7200}},
    'reviews-warm-dashboard-cache': {'task': 'apps.reviews.tasks.warm_dashboard_cache', 'schedule': crontab(hour=5, minute=0), 'options': {'expires': 3600}},
    'reviews-clear-stale-cache': {'task': 'apps.reviews.tasks.clear_stale_cache', 'schedule': crontab(hour=4, minute=0), 'options': {'expires': 3600}},
    'reviews-health-check': {'task': 'apps.reviews.tasks.reviews_health_check', 'schedule': crontab(minute='*/30'), 'options': {'expires': 1700}},
    'reviews-check-missing-reviews': {'task': 'apps.reviews.tasks.check_missing_reviews', 'schedule': crontab(day_of_week=1, hour=8, minute=0), 'options': {'expires': 86400}, 'kwargs': {'threshold_days': 7}},
    
    # Organization/Tenant Tasks
    'organization-reset-daily-api-counts': {'task': 'organization.reset_daily_api_counts', 'schedule': crontab(hour=0, minute=0), 'options': {'expires': 3600}},
    'organization-check-quota-warnings': {'task': 'organization.check_quota_warnings', 'schedule': crontab(minute='*/30'), 'options': {'expires': 1500}},
    'organization-sync-resource-limits-from-billing': {'task': 'organization.sync_resource_limits_from_billing', 'schedule': crontab(hour='*/6', minute=0), 'options': {'expires': 7200}},
    'organization-take-resource-snapshots-hourly': {'task': 'organization.take_resource_snapshots', 'schedule': crontab(minute=0), 'kwargs': {'snapshot_type': 'hourly'}, 'options': {'expires': 1800}},
    'organization-take-resource-snapshots-daily': {'task': 'organization.take_resource_snapshots', 'schedule': crontab(hour=1, minute=0), 'kwargs': {'snapshot_type': 'daily'}, 'options': {'expires': 3600}},
    'organization-forecast-resource-exhaustion': {'task': 'organization.forecast_resource_exhaustion', 'schedule': crontab(hour=2, minute=0), 'options': {'expires': 3600}},
    'organization-daily-maintenance': {'task': 'organization.run_daily_maintenance', 'schedule': crontab(hour=3, minute=0), 'options': {'expires': 7200}},
}