from rest_framework import serializers

class BillingSummarySerializer(serializers.Serializer):
    tenant_id = serializers.UUIDField()
    has_active_subscription = serializers.BooleanField()
    current_plan = serializers.DictField(required=False, allow_null=True)
    subscription_status = serializers.CharField(allow_null=True)
    trial_info = serializers.DictField(required=False)
    billing_info = serializers.DictField()
    recent_transactions = serializers.ListField()
    invoice_summary = serializers.DictField()
    total_spent = serializers.IntegerField()
    total_spent_display = serializers.CharField()

class RevenueReportSerializer(serializers.Serializer):
    period = serializers.CharField()
    start_date = serializers.DateField()
    end_date = serializers.DateField()
    total_revenue = serializers.IntegerField()
    total_revenue_display = serializers.CharField()
    total_transactions = serializers.IntegerField()
    successful_transactions = serializers.IntegerField()
    failed_transactions = serializers.IntegerField()
    success_rate = serializers.FloatField()
    breakdown = serializers.ListField()

class SubscriptionAnalyticsSerializer(serializers.Serializer):
    total_active = serializers.IntegerField()
    total_trialing = serializers.IntegerField()
    total_expired = serializers.IntegerField()
    total_cancelled = serializers.IntegerField()
    by_plan = serializers.DictField()
    by_plan_type = serializers.DictField()
    monthly_recurring_revenue = serializers.IntegerField()
    monthly_recurring_revenue_display = serializers.CharField()
    yearly_recurring_revenue = serializers.IntegerField()
    yearly_recurring_revenue_display = serializers.CharField()
    total_mrr = serializers.IntegerField()
    total_mrr_display = serializers.CharField()
    recent_activity = serializers.ListField()