"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.utils import timezone
from datetime import datetime, timedelta
import logging
import json

class JsonFormatter(logging.Formatter):
    def format(self, record):
        log_record = {
            'time': self.formatTime(record),
            'level': record.levelname,
            'module': record.module,
            'message': record.getMessage(),
        }
        return json.dumps(log_record)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    DJANGO_ENV=(str, 'development'),
    SECURE_SSL_REDIRECT=(bool, False),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SECURE=(bool, False),
    CORS_ALLOW_ALL_ORIGINS=(bool, False),
    RATELIMIT_ENABLE=(bool, True),
)


# .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-dev-key-not-for-production')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-_@-gd%1$i7%motr$)^ig)ue$a#ear_$wkbhtpsjh2f^pir0#+('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# ----------------------------------------------------------------------------
# ADMIN URL (Change from default for security)
# ----------------------------------------------------------------------------
ADMIN_URL = env('ADMIN_URL', default='admin/')


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

THIRD_PARTY_APPS = [
    # REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # CORS
    'corsheaders',
    # Multi-tenancy (RLS)
    'django_multitenant',
    'django_rls',
    # Security
    'axes',  # Login attempt monitoring
    'guardian',  # Object-level permissions
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    # Workflow
    # 'django_fsm',
    'viewflow',
    # Notifications
    'notifications',
    'django_apscheduler',
    # Reporting
    'easy_pdf',
    # Audit
    'auditlog',
    # API Documentation
    'drf_yasg',
    'drf_spectacular',
    # Async/Websockets
    'channels',
    # Websocket
    'celery',
    'django_celery_beat',
    'django_celery_results',
    'django_filters',
    # Health check
    'health_check',                             # required
    'health_check.db',                          # database checks
    'health_check.cache',                       # cache checks
    # 'health_check.storage',                     # storage checks
    # 'health_check.contrib.migrations',           # migration checks
]

PROJECT_APPS = [
    'apps.accounts.apps.AccountsConfig',
    'apps.core',
    'apps.dashboard',
    'apps.kpi',
    'apps.notification',
    'apps.organisations',
    'apps.reports',
    'apps.workflowsapi',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    # Security
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # Django core
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # MFA - after authentications
    'django_otp.middleware.OTPMiddleware',
    # Security and monitoring
    'axes.middleware.AxesMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'django_multitenant.middlewares.MultitenantMiddleware',
    # Rate limiting
    'django_ratelimit.middleware.RatelimitMiddleware',
    # Custom middleware
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='falcon_pms'),
        'USER': env('DB_USER', default='Dazlah'),
        'PASSWORD': env('DB_PASSWORD', default='Dazl6002'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
        'OPTIONS': {
            'options': '-c search_path=public',  # For RLS
        },
        # Connection pooling
        'CONN_MAX_AGE': 60,  # 60 seconds persistent connection
        'CONN_HEALTH_CHECKS': True,
    }
}

# DATABASE_ROUTERS = ['django_multitenant.middlewares.TenantRouter']

# ============================================================
# Frontend Configuration (for email links, redirects, etc.)
# ============================================================

# Base URL for the frontend application
# Used for:
# - Email verification links
# - Password reset links  
# - OAuth redirect URIs
# - Invitation links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Optional: Different URLs for different environments
FRONTEND_VERIFY_URL = os.environ.get('FRONTEND_VERIFY_URL', f"{FRONTEND_URL}/verify-email")
FRONTEND_RESET_PASSWORD_URL = os.environ.get('FRONTEND_RESET_PASSWORD_URL', f"{FRONTEND_URL}/reset-password")
FRONTEND_INVITE_URL = os.environ.get('FRONTEND_INVITE_URL', f"{FRONTEND_URL}/accept-invite")


# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTHENTICATION
# ----------------------------------------
AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Must be first for axes
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',  # Object-level permissions
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    # {'NAME': 'apps.accounts.validators.UppercaseValidator'},  # Custom
    # {'NAME': 'apps.accounts.validators.SpecialCharValidator'},  # Custom
]

# OAuth Configuration for SSO (Phase 5 - Advanced Features)
OAUTH_PROVIDERS = {
    # Google OAuth2
    'google': {
        'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
        'client_secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        'auth_url': 'https://accounts.google.com/o/oauth2/v2/auth',
        'token_url': 'https://oauth2.googleapis.com/token',
        'userinfo_url': 'https://www.googleapis.com/oauth2/v3/userinfo',
        'redirect_uri': os.environ.get('GOOGLE_REDIRECT_URI', ''),
        'scope': 'openid email profile',
        'state': None,  # Optional: for CSRF protection
    },
    
    # Microsoft / Azure AD OAuth2
    'microsoft': {
        'client_id': os.environ.get('MICROSOFT_CLIENT_ID', ''),
        'client_secret': os.environ.get('MICROSOFT_CLIENT_SECRET', ''),
        'auth_url': 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        'token_url': 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        'userinfo_url': 'https://graph.microsoft.com/v1.0/me',
        'redirect_uri': os.environ.get('MICROSOFT_REDIRECT_URI', ''),
        'scope': 'openid email profile User.Read',
        'state': None,
    },
    
    # GitHub OAuth2
    'github': {
        'client_id': os.environ.get('GITHUB_CLIENT_ID', ''),
        'client_secret': os.environ.get('GITHUB_CLIENT_SECRET', ''),
        'auth_url': 'https://github.com/login/oauth/authorize',
        'token_url': 'https://github.com/login/oauth/access_token',
        'userinfo_url': 'https://api.github.com/user',
        'redirect_uri': os.environ.get('GITHUB_REDIRECT_URI', ''),
        'scope': 'read:user user:email',
        'state': None,
    },
    
    # LinkedIn OAuth2
    'linkedin': {
        'client_id': os.environ.get('LINKEDIN_CLIENT_ID', ''),
        'client_secret': os.environ.get('LINKEDIN_CLIENT_SECRET', ''),
        'auth_url': 'https://www.linkedin.com/oauth/v2/authorization',
        'token_url': 'https://www.linkedin.com/oauth/v2/accessToken',
        'userinfo_url': 'https://api.linkedin.com/v2/userinfo',
        'redirect_uri': os.environ.get('LINKEDIN_REDIRECT_URI', ''),
        'scope': 'openid profile email',
        'state': None,
    },
    
    # Facebook OAuth2
    'facebook': {
        'client_id': os.environ.get('FACEBOOK_CLIENT_ID', ''),
        'client_secret': os.environ.get('FACEBOOK_CLIENT_SECRET', ''),
        'auth_url': 'https://www.facebook.com/v18.0/dialog/oauth',
        'token_url': 'https://graph.facebook.com/v18.0/oauth/access_token',
        'userinfo_url': 'https://graph.facebook.com/me',
        'redirect_uri': os.environ.get('FACEBOOK_REDIRECT_URI', ''),
        'scope': 'email public_profile',
        'state': None,
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi' # Kenya's local  time

USE_I18N = True

USE_TZ = True



# https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC & MEDIA FILES
#------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK CONFIGURATION

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'apps.accounts.api.v1.throttles.AnonRateThrottle',
        'apps.accounts.api.v1.throttles.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Base throttles
        'anon': '100/day',           # Anonymous users
        'user': '1000/day',          # Authenticated users
        # Auth endpoints
        'login': '5/minute',         # Login attempts
        'register': '3/hour',        # Registrations
        'password_reset': '3/hour',  # Password reset requests
        'email_verification': '2/hour',  # Email verification resend
        'session_refresh': '10/minute',  # Session refresh
        # MFA endpoints
        'mfa': '5/minute',           # MFA verification
        'mfa_enrollment': '3/hour',  # MFA enrollment
        'mfa_backup': '10/hour',     # Backup code attempts
        # Endpoint throttles
        'sensitive': '30/minute',    # Sensitive endpoints
        'admin': '200/hour',         # Admin endpoints
        'bulk': '5/hour',            # Bulk operations
        'report': '10/hour',         # Report generation
        # User management
        'user_creation': '5/hour',   # User signup
        'profile_update': '30/hour', # Profile updates
        'invitation': '20/hour',     # Invitation sending
        # Tenant throttles
        'tenant': '5000/hour',       # Per tenant overall
        'tenant_user_creation': '50/day',  # New users per tenant
        'tenant_api': '10000/day',   # API calls per tenant
    },
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'COERCE_DECIMAL_TO_STRING': False,
}

# JWT CONFIGURATION (with security best practices)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env.int('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', default=30)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env.int('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=7)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env('JWT_SIGNING_KEY', default=SECRET_KEY),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'FalconPMS',
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS CONFIGURATION
# ----------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CORS_ALLOW_ALL_ORIGINS = env('CORS_ALLOW_ALL_ORIGINS')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ----------------------------------------------------------------------------
# CSRF CONFIGURATION
# ----------------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
CSRF_COOKIE_HTTPONLY = True  # Not accessible via JavaScript
CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE')  # True in production with HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Store CSRF token in cookie (not session)

# ----------------------------------------------------------------------------
# SESSION CONFIGURATION
# ----------------------------------------------------------------------------
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # Use Redis
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE', default=1209600)  # 2 weeks
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE')  # True in production
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True  # Update session on each request

# ----------------------------------------------------------------------------
# CACHE CONFIGURATION (Redis)
# ----------------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_CLASS': 'redis.connection.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'timeout': 20,
            },
            'PASSWORD': env('REDIS_PASSWORD', default=None),
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'RETRY_ON_TIMEOUT': True,
            'HEALTH_CHECK_INTERVAL': 30,
        },
        'KEY_PREFIX': 'falcon',
        'TIMEOUT': 300,  # 5 minutes
    }
}

# CELERY CONFIGURATION (Task Queue)
# ----------------------------------------------------------------------------
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=env('REDIS_URL'))
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=env('REDIS_URL'))
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery Beat (scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# CHANNELS CONFIGURATION (WebSockets)
# ----------------------------------------------------------------------------
ASGI_APPLICATION = 'config.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [env('REDIS_URL')],
            'symmetric_encryption_keys': [SECRET_KEY],
            'capacity': 1000,
            'expiry': 60,
        },
    },
}

# LOGGING CONFIGURATION
# ----------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            '()': JsonFormatter,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'json',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'json',
        },
        'audit': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'audit.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
        'auditlog': {
            'handlers': ['audit', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ----------------------------------------------------------------------------
# AXES CONFIGURATION (Login attempt monitoring)
# ----------------------------------------------------------------------------
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5  # 5 failed attempts
AXES_COOLOFF_TIME = timedelta(minutes=15)  # 15 minute lockout
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True  # Reset counter on successful login

# Modern consolidated lockout parameters (replaces multiple deprecated settings)
AXES_LOCKOUT_PARAMETERS = [
    ['username', 'ip_address', 'user_agent'],  # Lock by combination
]
# AXES_ONLY_USER_FAILURES = False  # Track by username AND IP
# AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True

# ----------------------------------------------------------------------------
# DJANGO OTP (MFA) CONFIGURATION
# ----------------------------------------------------------------------------
OTP_TOTP_ISSUER = env('OTP_TOTP_ISSUER', default='FalconPMS')
OTP_TOTP_DIGITS = 6
OTP_TOTP_INTERVAL = 30  # 30 seconds

# ----------------------------------------------------------------------------
# AUDITLOG CONFIGURATION
# ----------------------------------------------------------------------------
AUDITLOG_INCLUDE_ALL_MODELS = True
AUDITLOG_EXCLUDE_TRACKING_MODELS = []  # Track everything

# ----------------------------------------------------------------------------
# RATE LIMITING
# ----------------------------------------------------------------------------
RATELIMIT_ENABLE = env('RATELIMIT_ENABLE')
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = 'apps.core.views.rate_limited'

# ----------------------------------------------------------------------------
# SITE ID (for multi-tenancy)
# ----------------------------------------------------------------------------
SITE_ID = 1

# ----------------------------------------------------------------------------
# EMAIL CONFIGURATION
# ----------------------------------------------------------------------------
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='operations@falconigc.com')

# ----------------------------------------------------------------------------
# API DOCUMENTATION (Swagger/OpenAPI)
# ----------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    'TITLE': 'Falcon PMS API',
    'DESCRIPTION': 'Performance Management System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v[0-9]',
    'SECURITY': [{'BearerAuth': []}],
    'TAGS': [
        {'name': 'auth', 'description': 'Authentication endpoints'},
    ],
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
}

# ----------------------------------------------------------------------------
# SECURITY HEADERS (enhanced in production)
# ----------------------------------------------------------------------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
SECURE_REFERRER_POLICY = 'same-origin'

# Content Security Policy (configured more strictly in production)
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'",)  # Allow inline for development
CSP_SCRIPT_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:",)
# ----------------------------------------------------------------------------
# STRIPE BILLING CONFIGURATION
# ----------------------------------------------------------------------------
STRIPE_PUBLIC_KEY = env('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')
